In [1]:
import tensorflow as tf
from sklearn.datasets import fetch_california_housing
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
fmnist = keras.datasets.fashion_mnist

In [3]:
(X_train, y_train), (X_test, y_test) = fmnist.load_data()

In [4]:
print(f'X_train :',X_train.shape)
print(f'X_test :',X_test.shape)
print(f'y_train :',y_train.shape)
print(f'y_test :',y_test.shape)

X_train : (60000, 28, 28)
X_test : (10000, 28, 28)
y_train : (60000,)
y_test : (10000,)


In [9]:
#plt.imshow(X_train[0], cmap = 'viridis')

In [6]:
#plt.imshow(y_train[0], cmap = 'gray')

In [7]:
#X_train[0]

In [8]:
#print(y_train[0])

Normalization

In [10]:
X_train=X_train/255
X_test=X_test/255

In [10]:
#X_train[0]

In [11]:
#plt.imshow(X_train[0], cmap = 'gray')

Model

In [11]:
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(100,activation='relu'))
model.add(keras.layers.Dense(75,activation='relu'))
model.add(keras.layers.Dense(10,activation='softmax'))

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 100)               78500     
                                                                 
 dense_1 (Dense)             (None, 75)                7575      
                                                                 
 dense_2 (Dense)             (None, 10)                760       
                                                                 
Total params: 86835 (339.20 KB)
Trainable params: 86835 (339.20 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


optimization

In [14]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [15]:
history = model.fit(X_train,y_train,epochs = 10,validation_split=0.15)

Epoch 1/10
1594/1594 [==============================] - 11s 6ms/step - loss: 0.7943 - accuracy: 0.7383 - val_loss: 0.5656 - val_accuracy: 0.8012
Epoch 2/10
1594/1594 [==============================] - 8s 5ms/step - loss: 0.5168 - accuracy: 0.8214 - val_loss: 0.4874 - val_accuracy: 0.8268
Epoch 3/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.4647 - accuracy: 0.8375 - val_loss: 0.4606 - val_accuracy: 0.8383
Epoch 4/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.4373 - accuracy: 0.8475 - val_loss: 0.4574 - val_accuracy: 0.8429
Epoch 5/10
1594/1594 [==============================] - 6s 4ms/step - loss: 0.4176 - accuracy: 0.8550 - val_loss: 0.4218 - val_accuracy: 0.8526
Epoch 6/10
1594/1594 [==============================] - 8s 5ms/step - loss: 0.4012 - accuracy: 0.8601 - val_loss: 0.4121 - val_accuracy: 0.8601
Epoch 7/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.3898 - accuracy: 0.8645 - val_loss: 0.4104 - val_accuracy

In [16]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test accuracy: {test_accuracy}')
print(f'Test loss: {test_loss}')


313/313 [==============================] - 1s 4ms/step - loss: 0.3960 - accuracy: 0.8609
Test accuracy: 0.8608999848365784
Test loss: 0.39601483941078186


In [17]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import numpy as np

# Get the model's predictions
y_pred = np.argmax(model.predict(X_test), axis=-1)

# Calculate Precision
precision = precision_score(y_test, y_pred, average='macro')
print(f'Precision: {precision}')

# Calculate Recall
recall = recall_score(y_test, y_pred, average='macro')
print(f'Recall: {recall}')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='macro')
print(f'F1 Score: {f1}')

# Calculate Confusion Matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix: \n{conf_mat}')


313/313 [==============================] - 1s 3ms/step
Precision: 0.8612902232566839
Recall: 0.8609
F1 Score: 0.8602674486639698
Confusion Matrix: 
[[848   1  19  30   3   1  86   0  12   0]
 [  3 956   5  27   3   0   5   0   1   0]
 [ 17   1 823  10  77   2  62   0   8   0]
 [ 32   7  16 865  35   0  40   0   5   0]
 [  1   0 148  27 727   1  87   0   9   0]
 [  0   0   1   0   0 929   0  51   2  17]
 [154   1 123  24  68   1 610   0  19   0]
 [  0   0   0   0   0  24   0 944   0  32]
 [  4   1   8   7   3   3  10   7 957   0]
 [  0   0   0   0   0  10   0  39   1 950]]


In [18]:
from sklearn.metrics import f1_score
import numpy as np

# Get the model's predictions
y_pred = np.argmax(model.predict(X_test), axis=-1)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred, average='macro')

print(f'F1 Score: {f1}')


313/313 [==============================] - 1s 3ms/step
F1 Score: 0.8602674486639698
