In [1]:
import tensorflow as tf
from sklearn.datasets import fetch_california_housing
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
fmnist = keras.datasets.fashion_mnist

In [3]:
(X_train, y_train), (X_test, y_test) = fmnist.load_data()

In [4]:
print(f'X_train :',X_train.shape)
print(f'X_test :',X_test.shape)
print(f'y_train :',y_train.shape)
print(f'y_test :',y_test.shape)

X_train : (60000, 28, 28)
X_test : (10000, 28, 28)
y_train : (60000,)
y_test : (10000,)


In [5]:
#plt.imshow(X_train[0], cmap = 'gray')

In [6]:
#plt.imshow(y_train[0], cmap = 'gray')

In [7]:
#X_train[0]

In [8]:
#print(y_train[0])

In [5]:
X_train=X_train/255
X_test=X_test/255

In [10]:
#X_train[0]

In [11]:
#plt.imshow(X_train[0], cmap = 'gray')

In [7]:
from keras.initializers import GlorotNormal
initializer_g = GlorotNormal(seed=None)
from keras.initializers import HeNormal
initializer_h = HeNormal(seed=None)

In [8]:
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(100,activation='relu',kernel_initializer=initializer_g))
model.add(keras.layers.Dense(75,activation='relu'))
model.add(keras.layers.Dense(10,activation='softmax'))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense (Dense)               (None, 100)               78500     
                                                                 
 dense_1 (Dense)             (None, 75)                7575      
                                                                 
 dense_2 (Dense)             (None, 10)                760       
                                                                 
Total params: 86835 (339.20 KB)
Trainable params: 86835 (339.20 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [11]:
history = model.fit(X_train,y_train,epochs = 10,validation_split=0.15)

Epoch 1/10
1594/1594 [==============================] - 8s 4ms/step - loss: 0.8089 - accuracy: 0.7274 - val_loss: 0.5719 - val_accuracy: 0.7961
Epoch 2/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.5145 - accuracy: 0.8217 - val_loss: 0.4892 - val_accuracy: 0.8308
Epoch 3/10
1594/1594 [==============================] - 9s 6ms/step - loss: 0.4613 - accuracy: 0.8394 - val_loss: 0.4526 - val_accuracy: 0.8417
Epoch 4/10
1594/1594 [==============================] - 11s 7ms/step - loss: 0.4325 - accuracy: 0.8492 - val_loss: 0.4363 - val_accuracy: 0.8488
Epoch 5/10
1594/1594 [==============================] - 10s 6ms/step - loss: 0.4114 - accuracy: 0.8559 - val_loss: 0.4448 - val_accuracy: 0.8406
Epoch 6/10
1594/1594 [==============================] - 7s 5ms/step - loss: 0.3946 - accuracy: 0.8618 - val_loss: 0.4140 - val_accuracy: 0.8562
Epoch 7/10
1594/1594 [==============================] - 11s 7ms/step - loss: 0.3809 - accuracy: 0.8657 - val_loss: 0.4452 - val_accura

In [12]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import numpy as np

# Get the model's predictions
y_pred = np.argmax(model.predict(X_test), axis=-1)

# Calculate Precision
precision = precision_score(y_test, y_pred, average='macro')
print(f'Precision: {precision}')

# Calculate Recall
recall = recall_score(y_test, y_pred, average='macro')
print(f'Recall: {recall}')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='macro')
print(f'F1 Score: {f1}')

# Calculate Confusion Matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix: \n{conf_mat}')


313/313 [==============================] - 1s 3ms/step
Precision: 0.8618849748396782
Recall: 0.8592000000000001
F1 Score: 0.8593699601125673
Confusion Matrix: 
[[801   1  10  34   4   1 134   0  15   0]
 [  3 964   1  23   4   0   4   0   1   0]
 [ 14   3 684  14 157   1 112   0  15   0]
 [ 27  11  10 850  50   0  46   0   6   0]
 [  0   1  62  19 832   0  76   0  10   0]
 [  0   0   0   1   0 925   0  47   5  22]
 [107   1  69  23  91   0 683   0  26   0]
 [  0   0   0   0   0  28   0 940   0  32]
 [  2   1   2   5   5   2  12   5 966   0]
 [  0   0   0   0   0  10   0  42   1 947]]


model 2

In [13]:
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(100,activation='relu',kernel_initializer=initializer_h))
model.add(keras.layers.Dense(75,activation='relu',kernel_initializer=initializer_h))
model.add(keras.layers.Dense(10,activation='softmax'))

C:\Anaconda\Lib\site-packages\keras\src\initializers\initializers.py:120: UserWarning: The initializer HeNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(


In [14]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [15]:
history = model.fit(X_train,y_train,epochs = 10,validation_split=0.15)

Epoch 1/10
1594/1594 [==============================] - 10s 5ms/step - loss: 0.7601 - accuracy: 0.7481 - val_loss: 0.5615 - val_accuracy: 0.7999
Epoch 2/10
1594/1594 [==============================] - 9s 6ms/step - loss: 0.5038 - accuracy: 0.8255 - val_loss: 0.4865 - val_accuracy: 0.8301
Epoch 3/10
1594/1594 [==============================] - 9s 6ms/step - loss: 0.4578 - accuracy: 0.8407 - val_loss: 0.4451 - val_accuracy: 0.8413
Epoch 4/10
1594/1594 [==============================] - 8s 5ms/step - loss: 0.4311 - accuracy: 0.8480 - val_loss: 0.4269 - val_accuracy: 0.8481
Epoch 5/10
1594/1594 [==============================] - 9s 5ms/step - loss: 0.4119 - accuracy: 0.8552 - val_loss: 0.4304 - val_accuracy: 0.8450
Epoch 6/10
1594/1594 [==============================] - 9s 6ms/step - loss: 0.3965 - accuracy: 0.8606 - val_loss: 0.4006 - val_accuracy: 0.8559
Epoch 7/10
1594/1594 [==============================] - 11s 7ms/step - loss: 0.3841 - accuracy: 0.8645 - val_loss: 0.3906 - val_accurac

In [16]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import numpy as np

# Get the model's predictions
y_pred = np.argmax(model.predict(X_test), axis=-1)

# Calculate Precision
precision = precision_score(y_test, y_pred, average='macro')
print(f'Precision: {precision}')

# Calculate Recall
recall = recall_score(y_test, y_pred, average='macro')
print(f'Recall: {recall}')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='macro')
print(f'F1 Score: {f1}')

# Calculate Confusion Matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix: \n{conf_mat}')


313/313 [==============================] - 1s 3ms/step
Precision: 0.8578035679054755
Recall: 0.8567
F1 Score: 0.8561232090479697
Confusion Matrix: 
[[807   0   8  77   4   2  91   1  10   0]
 [  3 951   3  36   3   0   3   0   1   0]
 [ 18   2 708  24 135   0 107   0   6   0]
 [ 20   6   7 923  18   1  22   0   3   0]
 [  0   0  76  64 766   1  89   0   4   0]
 [  0   0   0   1   0 936   0  43   2  18]
 [134   1  75  68  68   1 635   0  18   0]
 [  0   0   0   0   0  24   0 941   0  35]
 [  3   1   8  12   3   2  16   7 948   0]
 [  0   0   0   0   0   3   1  44   0 952]]


model 3

In [17]:
from keras.initializers import GlorotUniform
initializer_g = GlorotUniform(seed=None)
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(100,activation='relu',kernel_initializer=initializer_h))
model.add(keras.layers.Dense(75,activation='relu',kernel_initializer=initializer_h))
model.add(keras.layers.Dense(10,activation='softmax',kernel_initializer=initializer_g))

C:\Anaconda\Lib\site-packages\keras\src\initializers\initializers.py:120: UserWarning: The initializer HeNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(


In [18]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [19]:
history = model.fit(X_train,y_train,epochs = 10,validation_split=0.15)

Epoch 1/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.7700 - accuracy: 0.7420 - val_loss: 0.5755 - val_accuracy: 0.8028
Epoch 2/10
1594/1594 [==============================] - 9s 5ms/step - loss: 0.5067 - accuracy: 0.8240 - val_loss: 0.5243 - val_accuracy: 0.8136
Epoch 3/10
1594/1594 [==============================] - 10s 6ms/step - loss: 0.4581 - accuracy: 0.8401 - val_loss: 0.4538 - val_accuracy: 0.8389
Epoch 4/10
1594/1594 [==============================] - 12s 8ms/step - loss: 0.4302 - accuracy: 0.8495 - val_loss: 0.4400 - val_accuracy: 0.8406
Epoch 5/10
1594/1594 [==============================] - 11s 7ms/step - loss: 0.4098 - accuracy: 0.8559 - val_loss: 0.4253 - val_accuracy: 0.8482
Epoch 6/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.3944 - accuracy: 0.8618 - val_loss: 0.4046 - val_accuracy: 0.8543
Epoch 7/10
1594/1594 [==============================] - 9s 6ms/step - loss: 0.3809 - accuracy: 0.8651 - val_loss: 0.4520 - val_accura

In [20]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import numpy as np

# Get the model's predictions
y_pred = np.argmax(model.predict(X_test), axis=-1)

# Calculate Precision
precision = precision_score(y_test, y_pred, average='macro')
print(f'Precision: {precision}')

# Calculate Recall
recall = recall_score(y_test, y_pred, average='macro')
print(f'Recall: {recall}')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='macro')
print(f'F1 Score: {f1}')

# Calculate Confusion Matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix: \n{conf_mat}')


313/313 [==============================] - 1s 4ms/step
Precision: 0.8585832807521605
Recall: 0.8567
F1 Score: 0.8568049933303914
Confusion Matrix: 
[[735   4  22  56   3   2 165   1  12   0]
 [  0 962   2  29   2   0   3   0   2   0]
 [ 13   5 762  15 119   2  76   0   8   0]
 [ 14   8  11 900  25   0  39   0   3   0]
 [  0   2  90  43 757   1 100   0   7   0]
 [  0   0   0   1   0 936   0  46   1  16]
 [ 99   1  94  43  69   0 674   0  20   0]
 [  0   0   0   0   0  24   0 957   0  19]
 [  1   1   9   8   3   4  10   6 957   1]
 [  0   0   0   0   0  16   0  56   1 927]]
