In [1]:
import tensorflow as tf
from sklearn.datasets import fetch_california_housing
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score


In [2]:
fmnist = keras.datasets.fashion_mnist

In [3]:
(X_train, y_train), (X_test, y_test) = fmnist.load_data()

In [4]:
print(f'X_train :',X_train.shape)
print(f'X_test :',X_test.shape)
print(f'y_train :',y_train.shape)
print(f'y_test :',y_test.shape)

X_train : (60000, 28, 28)
X_test : (10000, 28, 28)
y_train : (60000,)
y_test : (10000,)


In [5]:
#plt.imshow(X_train[0], cmap = 'gray')

In [6]:
#plt.imshow(y_train[0], cmap = 'gray')

In [7]:
#X_train[0]

In [8]:
#print(y_train[0])

In [9]:
X_train = X_train/255
X_test = X_test/255

In [10]:
y_test.max()

9

In [11]:
#X_train[0]

In [12]:
#plt.imshow(X_train[0], cmap = 'gray')

In [13]:
from keras.initializers import GlorotNormal
initializer = GlorotNormal(seed=None)
from keras.initializers import HeNormal
initializer = HeNormal(seed=None)

In [14]:
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(100,activation='relu',kernel_initializer=initializer))
model.add(keras.layers.Dense(75,activation='relu'))
model.add(keras.layers.Dense(10,activation='softmax'))

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 100)               78500     
                                                                 
 dense_1 (Dense)             (None, 75)                7575      
                                                                 
 dense_2 (Dense)             (None, 10)                760       
                                                                 
Total params: 86835 (339.20 KB)
Trainable params: 86835 (339.20 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [17]:
history = model.fit(X_train,y_train,epochs = 10,validation_split=0.15)

Epoch 1/10
1594/1594 [==============================] - 8s 4ms/step - loss: 0.7674 - accuracy: 0.7476 - val_loss: 0.5428 - val_accuracy: 0.8161
Epoch 2/10
1594/1594 [==============================] - 6s 4ms/step - loss: 0.5037 - accuracy: 0.8244 - val_loss: 0.4878 - val_accuracy: 0.8269
Epoch 3/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.4570 - accuracy: 0.8398 - val_loss: 0.4681 - val_accuracy: 0.8312
Epoch 4/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.4300 - accuracy: 0.8486 - val_loss: 0.4304 - val_accuracy: 0.8456
Epoch 5/10
1594/1594 [==============================] - 6s 4ms/step - loss: 0.4090 - accuracy: 0.8558 - val_loss: 0.4203 - val_accuracy: 0.8543
Epoch 6/10
1594/1594 [==============================] - 6s 4ms/step - loss: 0.3933 - accuracy: 0.8628 - val_loss: 0.4072 - val_accuracy: 0.8537
Epoch 7/10
1594/1594 [==============================] - 7s 4ms/step - loss: 0.3811 - accuracy: 0.8652 - val_loss: 0.4078 - val_accuracy:

In [18]:
y_pred = model.predict(X_test)
y_pred

y_pred_class = np.argmax(y_pred, axis=1) 
y_pred_class

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_class)
print("Confusion Matrix:\n", cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print("Accuracy: ", accuracy)

# Precision
precision = precision_score(y_test, y_pred_class, average='weighted')
print("Precision: ", precision)

# Recall
recall = recall_score(y_test, y_pred_class, average='weighted')
print("Recall: ", recall)

# F1 Score
f1 = f1_score(y_test, y_pred_class, average='weighted')
print("F1 Score: ", f1)

# ROC AUC Score
# roc_auc = roc_auc_score(y_test, y_pred_class, multi_class='ovr')
# print("ROC AUC Score: ", roc_auc)


313/313 [==============================] - 1s 2ms/step
Confusion Matrix:
 [[731   2  13  49   7   1 182   0  15   0]
 [  2 955   2  31   6   0   3   0   1   0]
 [ 15   1 768   9 147   1  51   0   8   0]
 [ 14   8  17 873  49   0  32   0   7   0]
 [  0   0  91  19 851   1  32   0   6   0]
 [  0   0   0   1   0 955   0  32   2  10]
 [ 88   1 121  33 128   1 603   0  25   0]
 [  0   0   0   0   0  36   0 937   0  27]
 [  3   1   4   6   6   4   9   4 963   0]
 [  1   0   0   0   0  19   0  38   1 941]]
Accuracy:  0.8577
Precision:  0.8591263469440431
Recall:  0.8577
F1 Score:  0.8570959042388311


model 2

In [19]:
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(100,activation='relu',kernel_initializer=initializer))
model.add(keras.layers.Dense(75,activation='relu',kernel_initializer=initializer))
model.add(keras.layers.Dense(10,activation='softmax'))

C:\Anaconda\Lib\site-packages\keras\src\initializers\initializers.py:120: UserWarning: The initializer HeNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(


In [20]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [21]:
history = model.fit(X_train,y_train,epochs = 10,validation_split=0.15)

Epoch 1/10
1594/1594 [==============================] - 8s 4ms/step - loss: 0.7487 - accuracy: 0.7544 - val_loss: 0.5332 - val_accuracy: 0.8158
Epoch 2/10
1594/1594 [==============================] - 8s 5ms/step - loss: 0.4995 - accuracy: 0.8265 - val_loss: 0.4756 - val_accuracy: 0.8328
Epoch 3/10
1594/1594 [==============================] - 8s 5ms/step - loss: 0.4533 - accuracy: 0.8416 - val_loss: 0.4571 - val_accuracy: 0.8380
Epoch 4/10
1594/1594 [==============================] - 8s 5ms/step - loss: 0.4259 - accuracy: 0.8502 - val_loss: 0.4387 - val_accuracy: 0.8476
Epoch 5/10
1594/1594 [==============================] - 10s 6ms/step - loss: 0.4058 - accuracy: 0.8571 - val_loss: 0.4318 - val_accuracy: 0.8441
Epoch 6/10
1594/1594 [==============================] - 11s 7ms/step - loss: 0.3900 - accuracy: 0.8621 - val_loss: 0.3938 - val_accuracy: 0.8613
Epoch 7/10
1594/1594 [==============================] - 9s 6ms/step - loss: 0.3761 - accuracy: 0.8671 - val_loss: 0.3943 - val_accurac

In [22]:
y_pred = model.predict(X_test)
y_pred

y_pred_class = np.argmax(y_pred, axis=1) 
y_pred_class

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_class)
print("Confusion Matrix:\n", cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print("Accuracy: ", accuracy)

# Precision
precision = precision_score(y_test, y_pred_class, average='weighted')
print("Precision: ", precision)

# Recall
recall = recall_score(y_test, y_pred_class, average='weighted')
print("Recall: ", recall)

# F1 Score
f1 = f1_score(y_test, y_pred_class, average='weighted')
print("F1 Score: ", f1)

# ROC AUC Score
# roc_auc = roc_auc_score(y_test, y_pred_class, multi_class='ovr')
# print("ROC AUC Score: ", roc_auc)


313/313 [==============================] - 1s 3ms/step
Confusion Matrix:
 [[839   2  11  49   3   2  84   0  10   0]
 [  2 955   3  33   2   0   5   0   0   0]
 [ 19   3 702  16 165   1  91   0   3   0]
 [ 22   8   5 903  26   0  31   0   5   0]
 [  0   1  65  43 817   0  70   0   4   0]
 [  0   0   0   1   0 931   0  44   3  21]
 [149   3  83  37  85   1 625   0  17   0]
 [  0   0   0   0   0  16   0 942   0  42]
 [  6   1   8   7   5   2  11   6 954   0]
 [  0   0   0   0   0  11   1  36   0 952]]
Accuracy:  0.862
Precision:  0.8619629781680417
Recall:  0.862
F1 Score:  0.8610950008511643


model 3

In [23]:
from keras.initializers import GlorotUniform
from keras.activations import selu

initializer_g = GlorotUniform(seed=None)
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(100,activation=selu,kernel_initializer=initializer))
keras.layers.BatchNormalization()
model.add(keras.layers.Dense(75,activation=selu,kernel_initializer=initializer))
keras.layers.BatchNormalization()
model.add(keras.layers.Dense(10,activation='softmax',kernel_initializer=initializer_g))
keras.layers.BatchNormalization()


C:\Anaconda\Lib\site-packages\keras\src\initializers\initializers.py:120: UserWarning: The initializer HeNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(


In [24]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [25]:
history = model.fit(X_train,y_train,epochs = 30,validation_split=0.15)

Epoch 1/30
1594/1594 [==============================] - 7s 4ms/step - loss: 0.6018 - accuracy: 0.7929 - val_loss: 0.4756 - val_accuracy: 0.8297
Epoch 2/30
1594/1594 [==============================] - 6s 4ms/step - loss: 0.4584 - accuracy: 0.8365 - val_loss: 0.4456 - val_accuracy: 0.8391
Epoch 3/30
1594/1594 [==============================] - 6s 4ms/step - loss: 0.4268 - accuracy: 0.8483 - val_loss: 0.4299 - val_accuracy: 0.8471
Epoch 4/30
1594/1594 [==============================] - 7s 5ms/step - loss: 0.4051 - accuracy: 0.8568 - val_loss: 0.4153 - val_accuracy: 0.8477
Epoch 5/30
1594/1594 [==============================] - 6s 4ms/step - loss: 0.3891 - accuracy: 0.8618 - val_loss: 0.4077 - val_accuracy: 0.8540
Epoch 6/30
1594/1594 [==============================] - 6s 4ms/step - loss: 0.3758 - accuracy: 0.8662 - val_loss: 0.4155 - val_accuracy: 0.8484
Epoch 7/30
1594/1594 [==============================] - 6s 4ms/step - loss: 0.3660 - accuracy: 0.8714 - val_loss: 0.3731 - val_accuracy:

In [26]:
y_pred = model.predict(X_test)
y_pred

y_pred_class = np.argmax(y_pred, axis=1) 
y_pred_class

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_class)
print("Confusion Matrix:\n", cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print("Accuracy: ", accuracy)

# Precision
precision = precision_score(y_test, y_pred_class, average='weighted')
print("Precision: ", precision)

# Recall
recall = recall_score(y_test, y_pred_class, average='weighted')
print("Recall: ", recall)

# F1 Score
f1 = f1_score(y_test, y_pred_class, average='weighted')
print("F1 Score: ", f1)

# ROC AUC Score
# roc_auc = roc_auc_score(y_test, y_pred_class, multi_class='ovr')
# print("ROC AUC Score: ", roc_auc)


313/313 [==============================] - 1s 3ms/step
Confusion Matrix:
 [[805   2  12  24   2   1 145   0   8   1]
 [  2 965   0  24   3   0   5   0   1   0]
 [ 12   1 694  19 141   1 130   0   2   0]
 [ 25   9   7 893  23   0  38   0   5   0]
 [  0   1  51  43 796   0 107   0   2   0]
 [  0   0   0   1   0 937   0  37   2  23]
 [ 88   0  51  26  53   0 771   0  11   0]
 [  0   0   0   0   0  17   0 933   0  50]
 [  5   2   1   7   3   2  12   6 962   0]
 [  0   0   0   0   0   5   1  24   0 970]]
Accuracy:  0.8726
Precision:  0.8776693058121923
Recall:  0.8726
F1 Score:  0.8734968171168906


In [27]:
init_1 = keras.initializers.VarianceScaling(scale=2.0, mode='fan_avg')

In [28]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.Dense(100, activation='elu', kernel_initializer=init_1),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(75),
    keras.layers.LeakyReLU(alpha=0.3),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(10,activation='softmax')
])

In [29]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [30]:
history = model.fit(X_train,y_train,epochs = 30,validation_split=0.15)

Epoch 1/30
1594/1594 [==============================] - 9s 5ms/step - loss: 0.6218 - accuracy: 0.7838 - val_loss: 0.4689 - val_accuracy: 0.8349
Epoch 2/30
1594/1594 [==============================] - 7s 5ms/step - loss: 0.4656 - accuracy: 0.8359 - val_loss: 0.4327 - val_accuracy: 0.8499
Epoch 3/30
1594/1594 [==============================] - 8s 5ms/step - loss: 0.4241 - accuracy: 0.8498 - val_loss: 0.4033 - val_accuracy: 0.8588
Epoch 4/30
1594/1594 [==============================] - 8s 5ms/step - loss: 0.4009 - accuracy: 0.8566 - val_loss: 0.3870 - val_accuracy: 0.8631
Epoch 5/30
1594/1594 [==============================] - 7s 5ms/step - loss: 0.3831 - accuracy: 0.8636 - val_loss: 0.3820 - val_accuracy: 0.8616
Epoch 6/30
1594/1594 [==============================] - 8s 5ms/step - loss: 0.3695 - accuracy: 0.8681 - val_loss: 0.3742 - val_accuracy: 0.8680
Epoch 7/30
1594/1594 [==============================] - 7s 5ms/step - loss: 0.3575 - accuracy: 0.8713 - val_loss: 0.3743 - val_accuracy:

In [31]:
y_pred = model.predict(X_test)
y_pred

y_pred_class = np.argmax(y_pred, axis=1) 
y_pred_class

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_class)
print("Confusion Matrix:\n", cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print("Accuracy: ", accuracy)

# Precision
precision = precision_score(y_test, y_pred_class, average='weighted')
print("Precision: ", precision)

# Recall
recall = recall_score(y_test, y_pred_class, average='weighted')
print("Recall: ", recall)

# F1 Score
f1 = f1_score(y_test, y_pred_class, average='weighted')
print("F1 Score: ", f1)

# ROC AUC Score
# roc_auc = roc_auc_score(y_test, y_pred_class, multi_class='ovr')
# print("ROC AUC Score: ", roc_auc)


313/313 [==============================] - 1s 4ms/step
Confusion Matrix:
 [[764   4  10  21   3   1 187   0  10   0]
 [  2 974   2  14   3   0   4   0   1   0]
 [ 12   1 766  14 100   0 103   0   4   0]
 [ 14  19   8 868  32   0  54   0   5   0]
 [  0   1  71  30 806   1  84   0   7   0]
 [  0   0   0   1   0 949   0  31   3  16]
 [ 70   2  62  23  59   0 768   0  16   0]
 [  0   0   0   0   0  20   0 948   2  30]
 [  0   1   2   3   2   2  12   4 974   0]
 [  0   0   0   0   0   6   1  29   1 963]]
Accuracy:  0.878
Precision:  0.8829000264196648
Recall:  0.878
F1 Score:  0.8791682765666515


In [32]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, kernel_initializer=init_1,use_bias=False),
    keras.layers.BatchNormalization(),
    keras.layers.Activation("elu"),
    keras.layers.Dense(75,use_bias=False),
    keras.layers.BatchNormalization(),
    keras.layers.LeakyReLU(alpha=0.3),
    keras.layers.Dense(10,activation='softmax')
])

C:\Anaconda\Lib\site-packages\keras\src\initializers\initializers.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(


In [33]:
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'sgd',
    metrics=['accuracy']
             )

In [34]:
history = model.fit(X_train,y_train,epochs = 30,validation_split=0.15)

Epoch 1/30
1594/1594 [==============================] - 13s 7ms/step - loss: 0.6743 - accuracy: 0.7711 - val_loss: 0.4830 - val_accuracy: 0.8290
Epoch 2/30
1594/1594 [==============================] - 9s 5ms/step - loss: 0.4889 - accuracy: 0.8276 - val_loss: 0.4315 - val_accuracy: 0.8472
Epoch 3/30
1594/1594 [==============================] - 11s 7ms/step - loss: 0.4452 - accuracy: 0.8432 - val_loss: 0.4071 - val_accuracy: 0.8578
Epoch 4/30
1594/1594 [==============================] - 10s 6ms/step - loss: 0.4220 - accuracy: 0.8506 - val_loss: 0.3945 - val_accuracy: 0.8581
Epoch 5/30
1594/1594 [==============================] - 9s 5ms/step - loss: 0.4032 - accuracy: 0.8576 - val_loss: 0.3822 - val_accuracy: 0.8593
Epoch 6/30
1594/1594 [==============================] - 10s 6ms/step - loss: 0.3884 - accuracy: 0.8601 - val_loss: 0.3742 - val_accuracy: 0.8610
Epoch 7/30
1594/1594 [==============================] - 16s 10ms/step - loss: 0.3759 - accuracy: 0.8663 - val_loss: 0.3635 - val_acc

In [35]:
y_pred = model.predict(X_test)
y_pred

y_pred_class = np.argmax(y_pred, axis=1) 
y_pred_class

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_class)
print("Confusion Matrix:\n", cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print("Accuracy: ", accuracy)

# Precision
precision = precision_score(y_test, y_pred_class, average='weighted')
print("Precision: ", precision)

# Recall
recall = recall_score(y_test, y_pred_class, average='weighted')
print("Recall: ", recall)

# F1 Score
f1 = f1_score(y_test, y_pred_class, average='weighted')
print("F1 Score: ", f1)

# ROC AUC Score
# roc_auc = roc_auc_score(y_test, y_pred_class, multi_class='ovr')
# print("ROC AUC Score: ", roc_auc)


313/313 [==============================] - 2s 5ms/step
Confusion Matrix:
 [[847   5  18  32   4   1  87   0   5   1]
 [  2 967   3  20   3   0   4   0   1   0]
 [ 15   2 833  16  73   1  56   1   3   0]
 [ 23  17  17 873  36   2  27   0   5   0]
 [  0   1 108  29 795   2  63   0   2   0]
 [  0   0   0   1   0 944   0  36   2  17]
 [126   1 100  23  64   1 674   0  11   0]
 [  0   0   0   0   0  15   0 970   0  15]
 [ 11   1   6   5   4   2   7   6 958   0]
 [  1   0   0   0   0  11   1  52   0 935]]
Accuracy:  0.8796
Precision:  0.8797827767615995
Recall:  0.8796
F1 Score:  0.8792771181012072


# Gradient Clipping


In [40]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, kernel_initializer=init_1,use_bias=False),
    keras.layers.BatchNormalization(),
    keras.layers.Activation("elu"),
    keras.layers.Dense(75,use_bias=False),
    keras.layers.BatchNormalization(),
    keras.layers.LeakyReLU(alpha=0.3),
    keras.layers.Dense(10,activation='softmax')
])

In [41]:
sgd = keras.optimizers.SGD(clipvalue=1.0)
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=sgd,  # Corrected keyword here
              metrics=['accuracy'])


In [42]:
history = model.fit(X_train,y_train,epochs = 30,validation_split=0.15)

Epoch 1/30
1594/1594 [==============================] - 13s 7ms/step - loss: 0.6711 - accuracy: 0.7723 - val_loss: 0.4827 - val_accuracy: 0.8283
Epoch 2/30
1594/1594 [==============================] - 13s 8ms/step - loss: 0.4894 - accuracy: 0.8286 - val_loss: 0.4324 - val_accuracy: 0.8464
Epoch 3/30
1594/1594 [==============================] - 18s 11ms/step - loss: 0.4480 - accuracy: 0.8442 - val_loss: 0.4105 - val_accuracy: 0.8541
Epoch 4/30
1594/1594 [==============================] - 18s 11ms/step - loss: 0.4220 - accuracy: 0.8517 - val_loss: 0.3949 - val_accuracy: 0.8582
Epoch 5/30
1594/1594 [==============================] - 18s 11ms/step - loss: 0.4049 - accuracy: 0.8580 - val_loss: 0.3905 - val_accuracy: 0.8589
Epoch 6/30
1594/1594 [==============================] - 17s 10ms/step - loss: 0.3926 - accuracy: 0.8610 - val_loss: 0.3780 - val_accuracy: 0.8633
Epoch 7/30
1594/1594 [==============================] - 17s 11ms/step - loss: 0.3804 - accuracy: 0.8651 - val_loss: 0.3649 - v

In [43]:
y_pred = model.predict(X_test)
y_pred

y_pred_class = np.argmax(y_pred, axis=1) 
y_pred_class

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_class)
print("Confusion Matrix:\n", cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print("Accuracy: ", accuracy)

# Precision
precision = precision_score(y_test, y_pred_class, average='weighted')
print("Precision: ", precision)

# Recall
recall = recall_score(y_test, y_pred_class, average='weighted')
print("Recall: ", recall)

# F1 Score
f1 = f1_score(y_test, y_pred_class, average='weighted')
print("F1 Score: ", f1)

# ROC AUC Score
# roc_auc = roc_auc_score(y_test, y_pred_class, multi_class='ovr')
# print("ROC AUC Score: ", roc_auc)
